/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Yusha
 */
public class CalculatorJFrame extends javax.swing.JFrame {

    double num1, num2, ans; //variable declaration
    String operator;

    public CalculatorJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Display1 = new javax.swing.JTextField();
        jTextField_Display2 = new javax.swing.JTextField();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_multiply = new javax.swing.JButton();
        jButton_equal = new javax.swing.JButton();
        jButton_minus = new javax.swing.JButton();
        jButton_division = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_clearByOne = new javax.swing.JButton();
        jButton_tan = new javax.swing.JButton();
        jButton_sin = new javax.swing.JButton();
        jButton_cos = new javax.swing.JButton();
        jButton_squareRoot = new javax.swing.JButton();
        jButton_power = new javax.swing.JButton();
        jButton_point = new javax.swing.JButton();
        jButton_log = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_Display1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_Display1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Display1ActionPerformed(evt);
            }
        });

        jTextField_Display2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_6.setText("6");
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_7.setText("7");
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_8.setText("8");
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButton_9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_9.setText("9");
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_0.setText("0");
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });

        jButton_multiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_multiply.setText("x");
        jButton_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplyActionPerformed(evt);
            }
        });

        jButton_equal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_equal.setText("=");
        jButton_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_equalActionPerformed(evt);
            }
        });

        jButton_minus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton_minus.setText("-");
        jButton_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusActionPerformed(evt);
            }
        });

        jButton_division.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_division.setText("/");
        jButton_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divisionActionPerformed(evt);
            }
        });

        jButton_plus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_plus.setText("+");
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });

        jButton_clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_clear.setText("C");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_clearByOne.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_clearByOne.setText("<");
        jButton_clearByOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearByOneActionPerformed(evt);
            }
        });

        jButton_tan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_tan.setText("tan");
        jButton_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tanActionPerformed(evt);
            }
        });

        jButton_sin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_sin.setText("sin");
        jButton_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sinActionPerformed(evt);
            }
        });

        jButton_cos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_cos.setText("cos");
        jButton_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cosActionPerformed(evt);
            }
        });

        jButton_squareRoot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_squareRoot.setText(" √");
        jButton_squareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_squareRootActionPerformed(evt);
            }
        });

        jButton_power.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_power.setText("^");
        jButton_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_powerActionPerformed(evt);
            }
        });

        jButton_point.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_point.setText(".");
        jButton_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pointActionPerformed(evt);
            }
        });

        jButton_log.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_log.setText("log");
        jButton_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_Display1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_power, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_squareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_point, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_clearByOne, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_log, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_Display2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextField_Display1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Display2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_clearByOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_point, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_power, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_squareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_log, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Display1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Display1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Display1ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if (s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "2");
            } else {
                jTextField_Display1.setText("2"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "2"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_2ActionPerformed
    }
    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if(s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "5");
            }
            else{
            jTextField_Display1.setText("5"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "5"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_5ActionPerformed
    }
    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if(s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "8");
            }
            else{
                jTextField_Display1.setText("8"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "8"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_8ActionPerformed
    }
    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if(s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "4");
            }
            else{
                jTextField_Display1.setText("4"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "4"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_4ActionPerformed
    }
    private void jButton_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusActionPerformed
        if (jTextField_Display1.getText().equals("")) {
            jTextField_Display1.setText("-"); //showing unary minus
            num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1
            operator = "-";
        } else {
            num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
            jTextField_Display2.setText(num1 + " - "); //showing value to display 2
            jTextField_Display1.setText(""); //making display 1 empty
            operator = "-";
        }

    }//GEN-LAST:event_jButton_minusActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText(num1 + " + "); //showing value to display 2
        jTextField_Display1.setText(""); //making display 1 empty
        operator = "+";
    }//GEN-LAST:event_jButton_plusActionPerformed

    private void jButton_clearByOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearByOneActionPerformed
        int length = jTextField_Display1.getText().length(); //getting string size

        if (length > 0) {
            StringBuilder obj = new StringBuilder(jTextField_Display1.getText()); //creating string buider object to modify the string
            obj.deleteCharAt(length - 1);
            jTextField_Display1.setText(obj.toString());

        }

    }//GEN-LAST:event_jButton_clearByOneActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if (s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "1");
            } else {
                jTextField_Display1.setText("1");
            }
        } else {
            jTextField_Display1.setText(s + "1"); //Showing current digit with previous digits
        }
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if (s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "3");
            } else {
                jTextField_Display1.setText("3"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "3"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_3ActionPerformed
    }
    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if (s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "6");
            } else {
                jTextField_Display1.setText("6"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "6"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_6ActionPerformed
    }
    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if (s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "7");
            } else {
                jTextField_Display1.setText("7"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "7"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_7ActionPerformed
    }
    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            if (s.startsWith("0.")) //if it is 0 point something(0.05)
            {
                jTextField_Display1.setText(s + "9");
            } else {
                jTextField_Display1.setText("9"); //Show only current digit
            }
        } else {
            jTextField_Display1.setText(s + "9"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_9ActionPerformed
    }
    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        /*if (s.startsWith("0")) //if "0" is pressed first before any digits
        {
            jTextField_Display1.setText("0"); //Show only current digit
        } else {*/
        jTextField_Display1.setText(s + "0"); //Showing current digit with previous digits
    }//GEN-LAST:event_jButton_0ActionPerformed
    //}
    private void jButton_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText("log(" + num1 + ")"); //showing equation to display 2
        operator = "log";
    }//GEN-LAST:event_jButton_logActionPerformed

    private void jButton_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pointActionPerformed
        String s = jTextField_Display1.getText(); //Getting previous digits from display1
        if (s.indexOf(".") < 0) //checking for other points
        {
            jTextField_Display1.setText(s + "."); //Showing point with previous digits
    }//GEN-LAST:event_jButton_pointActionPerformed
    }
    private void jButton_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplyActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText(num1 + " x "); //showing value to display 2
        jTextField_Display1.setText(""); //making display 1 empty
        operator = "x";
    }//GEN-LAST:event_jButton_multiplyActionPerformed

    private void jButton_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divisionActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText(num1 + " / "); //showing value to display 2
        jTextField_Display1.setText(""); //making display 1 empty
        operator = "/";
    }//GEN-LAST:event_jButton_divisionActionPerformed

    private void jButton_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_equalActionPerformed
        String s = jTextField_Display2.getText(); //store display 2 string
        num2 = Double.parseDouble(jTextField_Display1.getText()); //assign num2 value;
        jTextField_Display2.setText(s + num2); //show the equation
        switch (operator) //calculator operation using switch case 
        {
            case "+": //for addition
                ans = num1 + num2;
                jTextField_Display1.setText(Double.toString(ans));
                break;
            case "-": //for subtruction
                if (jTextField_Display1.getText().startsWith("-")) //checking if unary minus is used
                {
                    ans = num1;
                    jTextField_Display1.setText(Double.toString(ans));
                } else {
                    ans = num1 - num2;
                    jTextField_Display1.setText(Double.toString(ans));
                }

                break;
            case "x": //for multiplication
                ans = num1 * num2;
                jTextField_Display1.setText(Double.toString(ans));
                break;
            case "/": //for divide
                if (num2 != 0) //checking if number 2 is 0
                {
                    ans = num1 / num2;
                    jTextField_Display1.setText(Double.toString(ans));
                } else {
                    jTextField_Display1.setText("Error");
                }
                break;
            case "√": //for square root
                ans = Math.sqrt(num1);
                jTextField_Display1.setText(Double.toString(ans));
                jTextField_Display2.setText(s);
                break;
            case "sin": //for sin theta
                num1 = Math.toRadians(num1); //converting degree into radian
                ans = Math.sin(num1);
                jTextField_Display1.setText(Double.toString(ans));
                jTextField_Display2.setText(s);
                break;
            case "cos": //for cos theta
                num1 = Math.toRadians(num1); //converting degree into radian
                ans = Math.cos(num1);
                jTextField_Display1.setText(Double.toString(ans));
                jTextField_Display2.setText(s);
                break;
            case "tan": //for tan theta
                if (num1 != 90) //checking if number 1 is 90 degree
                {
                    num1 = Math.toRadians(num1); //converting degree into radian
                    ans = Math.tan(num1);
                    jTextField_Display1.setText(Double.toString(ans));
                    jTextField_Display2.setText(s);
                } else {
                    jTextField_Display1.setText("Error");
                    jTextField_Display2.setText(s);
                }
                break;
            case "log": //for logarithm                
                ans = Math.log10(num1); //10 base logarithm
                jTextField_Display1.setText(Double.toString(ans));
                jTextField_Display2.setText(s);
                break;
            case "^": //for power function
                ans = Math.pow(num1, num2);
                jTextField_Display1.setText(Double.toString(ans));
                break;

        }
    }//GEN-LAST:event_jButton_equalActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        jTextField_Display1.setText(""); //Clear display1
        jTextField_Display2.setText(""); //Clear display2
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_squareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_squareRootActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText("√" + num1); //showing equation to display 2
        operator = "√";
    }//GEN-LAST:event_jButton_squareRootActionPerformed

    private void jButton_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sinActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText("sin(" + num1 + ")"); //showing equation to display 2
        operator = "sin";
    }//GEN-LAST:event_jButton_sinActionPerformed

    private void jButton_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cosActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText("cos(" + num1 + ")"); //showing equation to display 2
        operator = "cos";
    }//GEN-LAST:event_jButton_cosActionPerformed

    private void jButton_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tanActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText("tan(" + num1 + ")"); //showing equation to display 2
        operator = "tan";
    }//GEN-LAST:event_jButton_tanActionPerformed

    private void jButton_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_powerActionPerformed
        num1 = Double.parseDouble(jTextField_Display1.getText()); //assigning value to number 1 
        jTextField_Display2.setText(num1 + " ^ "); //showing value to display 2
        jTextField_Display1.setText(""); //making display 1 empty
        operator = "^";
    }//GEN-LAST:event_jButton_powerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculatorJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_clearByOne;
    private javax.swing.JButton jButton_cos;
    private javax.swing.JButton jButton_division;
    private javax.swing.JButton jButton_equal;
    private javax.swing.JButton jButton_log;
    private javax.swing.JButton jButton_minus;
    private javax.swing.JButton jButton_multiply;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_point;
    private javax.swing.JButton jButton_power;
    private javax.swing.JButton jButton_sin;
    private javax.swing.JButton jButton_squareRoot;
    private javax.swing.JButton jButton_tan;
    private javax.swing.JTextField jTextField_Display1;
    private javax.swing.JTextField jTextField_Display2;
    // End of variables declaration//GEN-END:variables
}
